# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sri/HRI_projects

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sri/HRI_projects

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sri/HRI_projects/CMakeFiles /home/sri/HRI_projects/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sri/HRI_projects/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dynamixel

# Build rule for target.
dynamixel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dynamixel
.PHONY : dynamixel

# fast build rule for target.
dynamixel/fast:
	$(MAKE) -f CMakeFiles/dynamixel.dir/build.make CMakeFiles/dynamixel.dir/build
.PHONY : dynamixel/fast

#=============================================================================
# Target rules for targets named datarecord

# Build rule for target.
datarecord: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 datarecord
.PHONY : datarecord

# fast build rule for target.
datarecord/fast:
	$(MAKE) -f CMakeFiles/datarecord.dir/build.make CMakeFiles/datarecord.dir/build
.PHONY : datarecord/fast

#=============================================================================
# Target rules for targets named gripper_demo

# Build rule for target.
gripper_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gripper_demo
.PHONY : gripper_demo

# fast build rule for target.
gripper_demo/fast:
	$(MAKE) -f CMakeFiles/gripper_demo.dir/build.make CMakeFiles/gripper_demo.dir/build
.PHONY : gripper_demo/fast

src/USB2Dynamixel.o: src/USB2Dynamixel.cpp.o

.PHONY : src/USB2Dynamixel.o

# target to build an object file
src/USB2Dynamixel.cpp.o:
	$(MAKE) -f CMakeFiles/dynamixel.dir/build.make CMakeFiles/dynamixel.dir/src/USB2Dynamixel.cpp.o
.PHONY : src/USB2Dynamixel.cpp.o

src/USB2Dynamixel.i: src/USB2Dynamixel.cpp.i

.PHONY : src/USB2Dynamixel.i

# target to preprocess a source file
src/USB2Dynamixel.cpp.i:
	$(MAKE) -f CMakeFiles/dynamixel.dir/build.make CMakeFiles/dynamixel.dir/src/USB2Dynamixel.cpp.i
.PHONY : src/USB2Dynamixel.cpp.i

src/USB2Dynamixel.s: src/USB2Dynamixel.cpp.s

.PHONY : src/USB2Dynamixel.s

# target to generate assembly for a file
src/USB2Dynamixel.cpp.s:
	$(MAKE) -f CMakeFiles/dynamixel.dir/build.make CMakeFiles/dynamixel.dir/src/USB2Dynamixel.cpp.s
.PHONY : src/USB2Dynamixel.cpp.s

src/datarecord.o: src/datarecord.cpp.o

.PHONY : src/datarecord.o

# target to build an object file
src/datarecord.cpp.o:
	$(MAKE) -f CMakeFiles/datarecord.dir/build.make CMakeFiles/datarecord.dir/src/datarecord.cpp.o
.PHONY : src/datarecord.cpp.o

src/datarecord.i: src/datarecord.cpp.i

.PHONY : src/datarecord.i

# target to preprocess a source file
src/datarecord.cpp.i:
	$(MAKE) -f CMakeFiles/datarecord.dir/build.make CMakeFiles/datarecord.dir/src/datarecord.cpp.i
.PHONY : src/datarecord.cpp.i

src/datarecord.s: src/datarecord.cpp.s

.PHONY : src/datarecord.s

# target to generate assembly for a file
src/datarecord.cpp.s:
	$(MAKE) -f CMakeFiles/datarecord.dir/build.make CMakeFiles/datarecord.dir/src/datarecord.cpp.s
.PHONY : src/datarecord.cpp.s

src/gripper.o: src/gripper.cpp.o

.PHONY : src/gripper.o

# target to build an object file
src/gripper.cpp.o:
	$(MAKE) -f CMakeFiles/gripper_demo.dir/build.make CMakeFiles/gripper_demo.dir/src/gripper.cpp.o
.PHONY : src/gripper.cpp.o

src/gripper.i: src/gripper.cpp.i

.PHONY : src/gripper.i

# target to preprocess a source file
src/gripper.cpp.i:
	$(MAKE) -f CMakeFiles/gripper_demo.dir/build.make CMakeFiles/gripper_demo.dir/src/gripper.cpp.i
.PHONY : src/gripper.cpp.i

src/gripper.s: src/gripper.cpp.s

.PHONY : src/gripper.s

# target to generate assembly for a file
src/gripper.cpp.s:
	$(MAKE) -f CMakeFiles/gripper_demo.dir/build.make CMakeFiles/gripper_demo.dir/src/gripper.cpp.s
.PHONY : src/gripper.cpp.s

src/utils.o: src/utils.cpp.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/dynamixel.dir/build.make CMakeFiles/dynamixel.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/dynamixel.dir/build.make CMakeFiles/dynamixel.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/dynamixel.dir/build.make CMakeFiles/dynamixel.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... dynamixel"
	@echo "... datarecord"
	@echo "... gripper_demo"
	@echo "... rebuild_cache"
	@echo "... src/USB2Dynamixel.o"
	@echo "... src/USB2Dynamixel.i"
	@echo "... src/USB2Dynamixel.s"
	@echo "... src/datarecord.o"
	@echo "... src/datarecord.i"
	@echo "... src/datarecord.s"
	@echo "... src/gripper.o"
	@echo "... src/gripper.i"
	@echo "... src/gripper.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

